name: PokebuilderLite
main: gg.pokebuilderlite.PokebuilderLite
version: 1.1.0
api-version: 1.16
commands:
  pr:
    description: precise move slot setter
    usage: /pr setmove <party 1-6> <slot 1-4> <move>
permissions:
  pokebuilder.admin:
    default: op
