name: build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven
      - run: mvn -B -DskipTests=true package
      - uses: actions/upload-artifact@v4
        with:
          name: pokebuilder-lite
          path: target/*.jar
